#!/usr/bin/env bash
# deploy.sh — One-shot WSL2 deployment for the autonomous assistant
#
# Run this once on the WSL2 machine. Safe to re-run — all steps are idempotent.
#
# What it does:
#   1. Checks prerequisites (Claude Code, Bun, tmux, git, curl, python3)
#   2. Builds gstack and registers skills
#   3. Adds upstream remote (garrytan/gstack) for future upgrades
#   4. Creates ~/.gstack/env with your credentials
#   5. Injects escalation policy + session memory into ~/.claude/CLAUDE.md
#   6. Adds tmux auto-start to ~/.bashrc
#   7. Registers cron jobs
#   8. Starts the webhook server and monitor in tmux
#   9. Runs a smoke test (Discord ping + webhook health check)
#
# Usage:
#   ./deploy.sh
#   ./deploy.sh --non-interactive   (uses existing ~/.gstack/env, no prompts)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$HOME/.gstack/env"
NON_INTERACTIVE=0
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=1

# ─── Colours ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
fail() { echo -e "${RED}✗${NC} $*"; exit 1; }
step() { echo -e "\n${GREEN}▶${NC} $*"; }

echo ""
echo "  Autonomous CEO's Assistant — WSL2 Deployment"
echo "  ============================================="
echo ""

# ─── Step 1: Prerequisites ────────────────────────────────────────────────────
step "Checking prerequisites..."

check_cmd() {
  if command -v "$1" >/dev/null 2>&1; then
    ok "$1 found ($(command -v "$1"))"
  else
    fail "$1 is required but not installed. $2"
  fi
}

check_cmd claude   "Install from https://docs.anthropic.com/en/docs/claude-code"
check_cmd bun      "Install with: curl -fsSL https://bun.sh/install | bash"
check_cmd tmux     "Install with: sudo apt install tmux"
check_cmd git      "Install with: sudo apt install git"
check_cmd curl     "Install with: sudo apt install curl"
check_cmd python3  "Install with: sudo apt install python3"

# Claude Code version check
CLAUDE_VERSION=$(claude --version 2>/dev/null | grep -oP '[\d.]+' | head -1 || echo "0")
if [[ "$(echo -e "2.1.80\n$CLAUDE_VERSION" | sort -V | head -1)" != "2.1.80" ]]; then
  warn "Claude Code version $CLAUDE_VERSION detected. 2.1.80+ recommended."
else
  ok "Claude Code $CLAUDE_VERSION"
fi

# ─── Step 1b: Xvfb virtual display (required for /qa and /browse in WSL2) ────
step "Setting up virtual display (Xvfb)..."
"$REPO_ROOT/scripts/xvfb-setup.sh"

# ─── Step 2: Build gstack and register skills ─────────────────────────────────
step "Building gstack and registering skills..."

cd "$REPO_ROOT"
./setup
ok "gstack built and skills registered."

# ─── Step 3: Upstream remote for upgrades ─────────────────────────────────────
step "Configuring git remotes..."

if git remote get-url upstream >/dev/null 2>&1; then
  ok "upstream remote already set ($(git remote get-url upstream))"
else
  git remote add upstream https://github.com/garrytan/gstack.git
  ok "Added upstream remote → garrytan/gstack"
fi

ok "origin → $(git remote get-url origin)"

# ─── Step 4: ~/.gstack/env ────────────────────────────────────────────────────
step "Configuring ~/.gstack/env..."

mkdir -p "$HOME/.gstack" "$HOME/.gstack/logs"

if [ "$NON_INTERACTIVE" -eq 0 ]; then
  # Load existing values as defaults
  [ -f "$ENV_FILE" ] && source "$ENV_FILE" 2>/dev/null || true

  echo ""
  echo "  Enter your configuration. Press Enter to keep existing value."
  echo ""

  read -rp "  Discord Webhook URL [${DISCORD_WEBHOOK_URL:-not set}]: " INPUT
  DISCORD_WEBHOOK_URL="${INPUT:-${DISCORD_WEBHOOK_URL:-}}"

  read -rp "  GitHub Webhook Secret [${GITHUB_WEBHOOK_SECRET:-not set}]: " INPUT
  GITHUB_WEBHOOK_SECRET="${INPUT:-${GITHUB_WEBHOOK_SECRET:-}}"

  read -rp "  Webhook port [${WEBHOOK_PORT:-9000}]: " INPUT
  WEBHOOK_PORT="${INPUT:-${WEBHOOK_PORT:-9000}}"

  read -rp "  Windows workspace path (e.g. C:\Projects\workspace) [${WINDOWS_WORKSPACE:-not set}]: " INPUT
  WINDOWS_WORKSPACE="${INPUT:-${WINDOWS_WORKSPACE:-}}"

  echo ""
fi

# Write env file
cat > "$ENV_FILE" <<EOF
# gstack autonomous assistant environment
# Generated by deploy.sh on $(date -I)
# Edit manually or re-run deploy.sh to update.

DISCORD_WEBHOOK_URL="${DISCORD_WEBHOOK_URL:-}"
GITHUB_WEBHOOK_SECRET="${GITHUB_WEBHOOK_SECRET:-}"
WEBHOOK_PORT="${WEBHOOK_PORT:-9000}"
WINDOWS_WORKSPACE="${WINDOWS_WORKSPACE:-}"
GSTACK_AUTO_UPGRADE="0"
GSTACK_REPO="$REPO_ROOT"
EOF

chmod 600 "$ENV_FILE"
ok "~/.gstack/env written (mode 600)."

if [ -z "${DISCORD_WEBHOOK_URL:-}" ]; then
  warn "DISCORD_WEBHOOK_URL not set — Discord notifications will not work until you add it."
fi
if [ -z "${GITHUB_WEBHOOK_SECRET:-}" ]; then
  warn "GITHUB_WEBHOOK_SECRET not set — webhook signature verification is disabled."
fi

# ─── Step 5: CLAUDE.md additions ─────────────────────────────────────────────
step "Updating ~/.claude/CLAUDE.md with escalation policy..."

mkdir -p "$HOME/.claude"
GLOBAL_CLAUDE_MD="$HOME/.claude/CLAUDE.md"

CLAUDE_ADDITIONS="$(cat "$REPO_ROOT/scripts/claude-md-additions.md")"
MARKER="<!-- gstack-autonomous-assistant -->"

if [ -f "$GLOBAL_CLAUDE_MD" ] && grep -q "$MARKER" "$GLOBAL_CLAUDE_MD"; then
  ok "Escalation policy already present in ~/.claude/CLAUDE.md"
else
  echo "" >> "$GLOBAL_CLAUDE_MD"
  echo "$MARKER" >> "$GLOBAL_CLAUDE_MD"
  echo "$CLAUDE_ADDITIONS" >> "$GLOBAL_CLAUDE_MD"
  ok "Escalation policy added to ~/.claude/CLAUDE.md"
fi

# ─── Step 6: .bashrc tmux auto-start ─────────────────────────────────────────
step "Adding tmux auto-start to ~/.bashrc..."

BASHRC="$HOME/.bashrc"
BASHRC_MARKER="# --- gstack tmux auto-start ---"

if grep -q "$BASHRC_MARKER" "$BASHRC" 2>/dev/null; then
  ok "tmux auto-start already in ~/.bashrc"
else
  cat >> "$BASHRC" <<BASHRC_EOF

$BASHRC_MARKER
if command -v tmux >/dev/null 2>&1 && [ -z "\${TMUX:-}" ] && [ -f "$ENV_FILE" ]; then
  if ! tmux has-session -t claudecore 2>/dev/null; then
    source "$ENV_FILE"
    tmux new-session -d -s claudecore \\
      "cd $REPO_ROOT && source $ENV_FILE && claude --channels plugin:discord@claude-plugins-official"
    sleep 3
    "$REPO_ROOT/webhook/start.sh" --tmux claudecore
    "$REPO_ROOT/scripts/monitor.sh" --tmux claudecore
    if command -v cloudflared >/dev/null 2>&1 && [ -f "\$HOME/.cloudflared/config.yml" ]; then
      tmux new-window -t claudecore -n "tunnel" \\
        "cloudflared tunnel run assistant 2>&1 | tee -a $HOME/.gstack/logs/tunnel.log"
    fi
    echo "  claudecore session started."
  fi
fi
# --- end gstack tmux auto-start ---
BASHRC_EOF
  ok "tmux auto-start added to ~/.bashrc"
fi

# ─── Step 7: Cron jobs ────────────────────────────────────────────────────────
step "Registering cron jobs..."
"$REPO_ROOT/scripts/cron-setup.sh"
ok "Cron jobs registered."

# ─── Step 8: Start tmux session ───────────────────────────────────────────────
step "Starting tmux session..."

source "$ENV_FILE"

if tmux has-session -t claudecore 2>/dev/null; then
  ok "claudecore session already running."
else
  tmux new-session -d -s claudecore \
    "cd $REPO_ROOT && source $ENV_FILE && claude --channels plugin:discord@claude-plugins-official"
  sleep 3
  ok "claudecore session started."

  "$REPO_ROOT/webhook/start.sh" --tmux claudecore
  ok "Webhook server started (tmux window: webhook)."

  "$REPO_ROOT/scripts/monitor.sh" --tmux claudecore
  ok "Monitor started (tmux window: monitor)."

  # Start Cloudflare Tunnel if configured
  if command -v cloudflared >/dev/null 2>&1 && [ -f "$HOME/.cloudflared/config.yml" ]; then
    tmux new-window -t claudecore -n "tunnel" \
      "cloudflared tunnel run assistant 2>&1 | tee -a $HOME/.gstack/logs/tunnel.log"
    ok "Cloudflare Tunnel started (tmux window: tunnel)."
  else
    warn "Cloudflare Tunnel not configured. Run scripts/cloudflare-setup.sh first, then re-run deploy.sh."
  fi
fi

# ─── Step 9: Smoke test ───────────────────────────────────────────────────────
step "Running smoke tests..."

# Discord ping
if [ -n "${DISCORD_WEBHOOK_URL:-}" ]; then
  if "$REPO_ROOT/scripts/discord-notify.sh" "🚀 Autonomous assistant deployed and running. gstack is ready." 2>/dev/null; then
    ok "Discord notification sent."
  else
    warn "Discord notification failed — check DISCORD_WEBHOOK_URL."
  fi
else
  warn "Skipping Discord test — DISCORD_WEBHOOK_URL not set."
fi

# Webhook health check
sleep 2
if curl -sf "http://localhost:${WEBHOOK_PORT:-9000}/health" >/dev/null 2>&1; then
  ok "Webhook server healthy at port ${WEBHOOK_PORT:-9000}."
else
  warn "Webhook server not responding yet — it may still be starting. Check: tmux select-window -t claudecore:webhook"
fi

# ─── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}  Deployment complete.${NC}"
echo ""
echo "  Tmux session:   tmux attach -t claudecore"
echo "  Webhook logs:   tail -f ~/.gstack/logs/webhook.log"
echo "  Heartbeat logs: tail -f ~/.gstack/logs/heartbeat.log"
echo "  Monitor logs:   tail -f ~/.gstack/logs/monitor.log"
echo ""
echo "  Add projects to: $REPO_ROOT/projects/QUEUE.md"
echo "  Upgrade gstack:  /gstack-upgrade  (or runs automatically on Mondays)"
echo ""
